<h1 style="color:#F4EE00; font-family:cambria"><i>Multi-Layered, Feedforward Neural Network</i></h1>

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>This is a multi-layred, feedforward neural network written from scratch in Python.</i>
</span>
<hr>

<img src="neuralnetwork.png" width=50%>

<h2 style="color:#F4EE00; font-family:cambria"><i>Importing Libraries</i></h2>
<hr>

In [1]:
import numpy as np
from time import time
import matplotlib.pyplot as plt
from typing import Any, Dict, List, Tuple, TypedDict, Union
from nptyping import NDArray, Float64
np.seterr( over = 'raise' )

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

<h2 style="color:#F4EE00; font-family:cambria"><i>Defining Data Structures</i></h2>
<hr>

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>Input Matrix</i>
</span>
<br>
<br>
<span style="font-size:24px">$
\color{blue}{X} = \begin{bmatrix}
    \color{blue}{x_{1,1}} & \color{blue}{x_{1,2}} & \dots & \color{blue}{x_{1,n}} \\
    \color{blue}{x_{2,1}} & \color{blue}{x_{2,2}} & \dots & \color{blue}{x_{2,n}} \\
    \vdots & \vdots & \ddots & \vdots \\
    \color{blue}{x_{m,1}} & \color{blue}{x_{m,2}} & \dots & \color{blue}{x_{m,n}} \\
\end{bmatrix}
$</span>

In [2]:
Examples = Any
Features = Any
Input_Matrix = NDArray[ ( Examples, Features ), Float64 ]

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>Target Matrix</i>
</span>
<br>
<br>
<span style="font-size:24px">$
\color{yellow}{Y} = \begin{bmatrix}
    \color{yellow}{y_{1,1}} & \color{yellow}{y_{1,2}} & \dots & \color{yellow}{y_{1,k}} \\
    \color{yellow}{y_{2,1}} & \color{yellow}{y_{2,2}} & \dots & \color{yellow}{y_{2,k}} \\
    \vdots & \vdots & \ddots & \vdots \\
    \color{yellow}{y_{m,1}} & \color{yellow}{y_{m,2}} & \dots & \color{yellow}{y_{m,k}}
\end{bmatrix}
$</span>

In [3]:
Targets = Any
Target_Matrix = NDArray[ ( Examples, Targets ), Float64 ]

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>Output</i>
</span>
<br>
<br>
<span style="font-size:24px">$
\color{yellow}{\hat{Y}} = \begin{bmatrix}
    \color{yellow}{\hat{y}_{1,1}} & \color{yellow}{\hat{y}_{1,2}} & \dots & \color{yellow}{\hat{y}_{1,k}} \\
    \color{yellow}{\hat{y}_{2,1}} & \color{yellow}{\hat{y}_{2,2}} & \dots & \color{yellow}{\hat{y}_{2,k}} \\
    \vdots & \vdots & \ddots & \vdots \\
    \color{yellow}{\hat{y}_{m,1}} & \color{yellow}{\hat{y}_{m,2}} & \dots & \color{yellow}{\hat{y}_{m,k}}
\end{bmatrix}
$

In [4]:
Output_Matrix = NDArray[ ( Examples, Targets ), Float64 ]

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>Perceptron</i>
</span>
<br>
<br>
<span style="font-size:24px">$
\color{green}{P}^{(ℓ)}_{\color{green}{k}} = \begin{bmatrix}
    \color{green}{\omega}^{(ℓ)}_{\color{green}{1,k}} \\
    \color{green}{\omega}^{(ℓ)}_{\color{green}{2,k}} \\
    \vdots \\ 
    \color{green}{\omega}^{(ℓ)}_{\color{green}{j,k}}
\end{bmatrix} \\
\color{green}{b}^{(ℓ)}_{\color{green}{k}} = \color{green}{\omega}^{(ℓ)}_{\color{green}{0,k}}
$

In [5]:
Inputs = Any
Bias, Weight = Float64, Float64
Perceptron = NDArray[ ( Inputs, 1 ), Weight ]

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>Layer</i>
</span>
<br>
<br>
<span style="font-size:24px">$
\color{green}{\Omega}^{(ℓ)} = \begin{bmatrix}
    \color{green}{P}^{(ℓ)}_{\color{green}{1}} & 
    \color{green}{P}^{(ℓ)}_{\color{green}{2}} & 
    \dots & 
    \color{green}{P}^{(ℓ)}_{\color{green}{k}}
\end{bmatrix} \\
\color{green}{\beta}^{(ℓ)} = \begin{bmatrix}
    \color{green}{b}^{(ℓ)}_{\color{green}{1}} & 
    \color{green}{b}^{(ℓ)}_{\color{green}{2}} & 
    \dots & 
    \color{green}{b}^{(ℓ)}_{\color{green}{k}}
\end{bmatrix}
$</span>

In [6]:
Number_of_Perceptrons = Any
Weights = NDArray[ ( Inputs, Number_of_Perceptrons ), Perceptron ]
Biases = NDArray[ Number_of_Perceptrons, Bias ]

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>Neural Network</i>
</span>
<br>
<br>
<span style="font-size:24px">$
\color{green}{N} = \begin{bmatrix}
    \begin{bmatrix}
       \color{green}{\Omega}^{(1)} &
       \color{green}{\Omega}^{(2)} & 
       \dots & 
       \color{green}{\Omega}^{(ℓ)}
   \end{bmatrix} & 
   \begin{bmatrix}
       \color{green}{\beta}^{(1)} &
       \color{green}{\beta}^{(2)} & 
       \dots & 
       \color{green}{\beta}^{(ℓ)}
   \end{bmatrix}
\end{bmatrix}
$</span>

In [7]:
Network_Weights = Dict[ int, Weights ]
Network_Biases = Dict[ int, Biases ]
class Network( TypedDict ) :
    weights : Network_Weights
    biases  : Network_Biases

<h1 style="color:#F4EE00; font-family:cambria"><i>Creating the Neural Network</i></h1>
<hr>

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>Initialization</i>
</span>

In [8]:
class FeedForwardNeuralNetwork :
    
    def __init__( self, perceptrons_per_hidden_layer : List[ int ] = [] ) -> None :
        self.score = 0.0
        self.perlayer = perceptrons_per_hidden_layer
        self.network : Network = { 'weights' : {}, 'biases' : {} }
        return

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>Initialize Random Weights and Biases</i>
</span>

In [9]:
class FeedForwardNeuralNetwork( FeedForwardNeuralNetwork  ) :
    
    def initialize( self, X : Input_Matrix, Y : Target_Matrix ) -> None :
        inputs, layer = X.shape[ 1 ], 1
        self.network = { 'weights' : {}, 'biases' : {} }
        for perceptrons in self.perlayer :
            self.network[ 'weights' ][ layer ] = np.random.rand( inputs, perceptrons )
            self.network[ 'biases' ][ layer ] = np.random.rand( perceptrons )
            inputs = perceptrons
            layer += 1
        self.network[ 'weights' ][ layer ] = np.random.rand( inputs, Y.shape[ 1 ] )
        self.network[ 'biases' ][ layer ] = np.random.rand( Y.shape[ 1 ] )
        return

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>Activation Function</i>
</span>
<br>
<br>
<table align="left">
    <tr>
        <td style="font-size:14px">$\color{blue}{Sigmoid}$</td>
        <td style="font-size:24px; text-align:left">$
        \color{pink}{f}(x) = \frac{1}{1+\color{blue}{e}^{-x}}
        $</td>
    </tr>
    <tr>
        <td style="font-size:14px">$\color{blue}{Derivative}$</td>
        <td style="font-size:24px">$
        \color{pink}{f}(x) = \frac{\color{blue}{e}^{-x}}{(1+\color{blue}{e}^{-x})^{2}}
        $</td>
    </tr>
</table>

In [10]:
class FeedForwardNeuralNetwork( FeedForwardNeuralNetwork  ) :
    
    def activation( self, L : Input_Matrix ) -> Union[ NDArray[ Float64 ], Float64 ] :
        return 1.0 / ( 1.0 + np.exp( -L ) )
    
    def derivative( self, L : Input_Matrix ) -> Union[ NDArray[ Float64 ], Float64 ] :
        return np.exp( -L ) / np.square( 1.0 + np.exp( -L ) )

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>Cost and Gradient</i>
</span>
<br>
<br>
<table align="left">
    <tr>
        <td style="font-size:14px">$\color{blue}{Cost\ Function}$</td>
        <td style="font-size:24px">$
        \color{pink}{C}(\color{yellow}{Y};\color{yellow}{\hat{Y}}) = 
        \sum_{h=1}^{m}{\sum_{i=1}^{k} (\color{yellow}{\hat{y}}_{h,i} - \color{yellow}{y}_{h,i}})^{2} =
        \sum_{h=1}^{m}{\sum_{i=1}^{k} (\color{pink}{a}^{(ℓ)}_{h,i} - \color{yellow}{y}_{h,i}})^{2} 
        $</td>
    </tr>
    <tr>
        <td style="font-size:14px">$\color{blue}{Gradient}$</td>
        <td style="font-size:24px; text-align:left">$
        \nabla^{(ℓ)}_{\color{pink}{a}}\color{pink}{C} = \begin{bmatrix}
                \frac{\partial \color{pink}{C}}{\partial \color{pink}{a}^{(ℓ)}_{\color{pink}{1,1}}} &
                \frac{\partial \color{pink}{C}}{\partial \color{pink}{a}^{(ℓ)}_{\color{pink}{1,2}}} &
                \dots & 
                \frac{\partial \color{pink}{C}}{\partial \color{pink}{a}^{(ℓ)}_{\color{pink}{1,k}}} 
                \\
                \frac{\partial \color{pink}{C}}{\partial \color{pink}{a}^{(ℓ)}_{\color{pink}{2,1}}} &
                \frac{\partial \color{pink}{C}}{\partial \color{pink}{a}^{(ℓ)}_{\color{pink}{2,2}}} &
                \dots & 
                \frac{\partial \color{pink}{C}}{\partial \color{pink}{a}^{(ℓ)}_{\color{pink}{2,k}}}
                \\
                \vdots & \vdots & \ddots & \vdots \\
                \\
                \frac{\partial \color{pink}{C}}{\partial \color{pink}{a}^{(ℓ)}_{\color{pink}{m,1}}} &
                \frac{\partial \color{pink}{C}}{\partial \color{pink}{a}^{(ℓ)}_{\color{pink}{m,2}}} &
                \dots & 
                \frac{\partial \color{pink}{C}}{\partial \color{pink}{a}^{(ℓ)}_{\color{pink}{m,k}}}
            \end{bmatrix} = 2(\color{yellow}{\hat{Y}}-\color{yellow}{Y}) 
        $</td>
    </tr>
</table>

In [11]:
class FeedForwardNeuralNetwork( FeedForwardNeuralNetwork  ) :
    
    def cost( self, A : Output_Matrix, Y : Target_Matrix ) -> Float64 :
        return np.square( A - Y ).sum()
    
    def grad( self, A : Output_Matrix, Y : Target_Matrix ) -> NDArray :
        return 2*( A - Y )

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>Forward Propagation</i>
</span>
<br>
<br>
<table align="left">
    <tr>
        <td style="font-size:14px">$\color{blue}{Output\ and\ Hidden\ Layer}$</td>
        <td style="font-size:24px">$
            \color{blue}{L}^{(ℓ)}=
            \color{red}{f}⊙(\color{blue}{L}^{(ℓ-1)}\color{green}{\Omega}^{ℓ} + \color{green}{\beta}^{ℓ})
            $
        </td>
    </tr>
    <tr>
        <td style="font-size:14px">$\color{blue}{Input Layer}$</td>
        <td style="font-size:24px; text-align:left">$\color{blue}{L}^{(0)} = \color{blue}{X}$</td>
    </tr>
</table>

In [12]:
class FeedForwardNeuralNetwork( FeedForwardNeuralNetwork  ) :
    
    def forwardpropagation( self, L : Input_Matrix ) -> Output_Matrix :
        for layer in range( 1, len( self.network[ 'weights' ] ) + 1 ) :
            L = self.activation( 
                np.matmul( L, self.network[ 'weights' ][ layer ] ) \
                + self.network[ 'biases' ][ layer ] 
                ) 
        return L

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>Backpropagation</i>
</span>
<br>
<br>
<table align="left">
    <tr>
        <td style="font-size:14px">$\color{blue}{Containers}$</td>
        <td style="font-size:24px; text-align:left">
            $
            \color{orange}{Z}[ℓ] = \color{blue}{L}^{(ℓ-1)}\color{green}{\Omega}^{(ℓ)}+\color{green}{\beta}^{(ℓ)} \\
            \color{pink}{A}[ℓ] = \color{blue}{L}^{(ℓ)}
            $
        </td>
    </tr>
</table>

In [13]:
class FeedForwardNeuralNetwork( FeedForwardNeuralNetwork  ) :
    
    def __forwardpropagation( self, X : Input_Matrix, A : Dict, Z : Dict ) -> Output_Matrix :
        A[ 0 ] = X
        for layer in range( 1, len( self.network[ 'weights' ] ) + 1 ) :
            # weighted input to layer
            Z[ layer ] = np.matmul( A[ layer - 1 ], self.network[ 'weights' ][ layer ] ) \
                         + self.network[ 'biases' ][ layer ]
            # output of layer
            A[ layer ] = self.activation( Z[ layer ] )
        return A[ layer ]

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>Backpropagation</i>
</span>
<br>
<br>
<table align="left">
    <tr>
        <td style="font-size:14px">$\color{blue}{Initialization}$</td>
        <td style="font-size:24px; text-align:left">
            $
            \nabla^{(ℓ)}_{\color{orange}{z}}\color{pink}{C}=
            (\color{pink}{f}'⊙\color{orange}{Z}[ℓ])⊙\nabla^{(ℓ)}_{\color{pink}{a}}\color{pink}{C}
            $
        </td>
    </tr>
    <tr>
        <td style="font-size:14px">$\color{blue}{Output\ and\ Hidden\ Layer}$</td>
        <td style="font-size:24px">
            $
            \nabla^{(ℓ)}_{\color{green}{\Omega}}\color{pink}{C}=
            \color{pink}{A}[ℓ-1]^{T}\nabla^{(ℓ)}_{\color{orange}{z}}\color{pink}{C} \\
            \nabla^{(ℓ)}_{\color{green}{\beta}}\color{pink}{C}=
            1_{1\times m}\nabla^{(ℓ)}_{\color{orange}{z}}\color{pink}{C} \\
            \nabla^{(ℓ-1)}_{\color{orange}{z}}\color{pink}{C}=
            (\color{pink}{f}'⊙\color{orange}{Z}[ℓ-1])⊙\nabla^{(ℓ)}_{\color{orange}{z}}\color{pink}{C}(\color{green}{\Omega}^{(ℓ)})^{T}
            $
        </td>
    </tr>
</table>

In [15]:
class FeedForwardNeuralNetwork( FeedForwardNeuralNetwork  ) :
    
    def backpropagate( self, grad_z : NDArray, A : Dict, Z : Dict, layer : int ) -> Tuple :
        # gradient with respect to the weights of the layer
        grad_w = np.matmul( A[ layer - 1 ].T, grad_z ) / len( grad_z )
        # gradient with respect to the biases of the layer
        grad_b = grad_z.mean( axis = 0 )
        # gradient with respect to the weighted input of the layer
        if layer > 1 : # there is no weighted input for layer 1
            grad_z = self.derivative( Z[ layer - 1 ] ) *\
                     np.matmul( grad_z, self.network[ 'weights' ][ layer ].T )
        return grad_z, grad_w, grad_b

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>Training Algorithm</i>
</span>
<br>
<br>
<span style="font-size:24px">$
\color{green}{\Omega}^{(ℓ)} \rightarrow \color{green}{\Omega}^{(ℓ)} - r\nabla^{(ℓ)}_{\color{green}{\Omega}}\color{pink}{C} \\
\color{green}{\beta}^{(ℓ)} \rightarrow \color{green}{\beta}^{(ℓ)} - r\nabla^{(ℓ)}_{\color{green}{\beta}}\color{pink}{C}
$</span>

In [16]:
class FeedForwardNeuralNetwork( FeedForwardNeuralNetwork  ) :
    
    def train( self, X : Input_Matrix, Y : Target_Matrix, 
               learning_rate = 1.0, convergence = 0.01, 
               batch_size = 100, max_epoch = 500, max_time = 60 ) -> None :
        ''' Stochastic Gradient Descent '''
        epoch = 1
        A, Z = {}, {}
        start = time()
        totgrad = np.inf
        self.initialize( X, Y )
        output_layer = len( self.network[ 'weights' ] )
        while np.sqrt( totgrad ) > convergence :
            totgrad = 0
            shuffle = np.random.permutation( len( X ) )
            X, Y = X[ shuffle ], Y[ shuffle ]
            for batch_x, batch_y in zip( 
                np.array_split( X, len( X ) // batch_size ), 
                np.array_split( Y, len( Y ) // batch_size ) 
                ) :
                output = self.__forwardpropagation( batch_x, A, Z )
                # gradient with respect to the output layer
                grad_a = self.grad( output, batch_y )
                totgrad += np.linalg.norm( grad_a )**2
                # gradient with respect to the weighted input of the output layer
                grad_z = self.derivative( Z[ output_layer ] ) * grad_a
                for layer in range( output_layer, 0, -1 ) :
                    grad_z, grad_w, grad_b = self.backpropagate( grad_z, A, Z, layer )
                    # updating the weights and biases of layer
                    self.network[ 'weights' ][ layer ] -= learning_rate * grad_w
                    self.network[ 'biases' ][ layer ] -= learning_rate * grad_b
            epoch += 1
            if time() - start > max_time :
                print( 'Maximum runtime encountered.' )
                break
            if epoch > max_epoch :
                print( 'Maximum epoch encountered.' )
                break
        self.score = self.cost( self.forwardpropagation( X ), Y )
        return

<h1 style="color:#F4EE00; font-family:cambria"><i>Test Drive on MNIST Data!</i></h1>
<hr>

In [17]:
train = np.loadtxt( 'mnist_train.csv', delimiter = ',', skiprows = 1 )

In [18]:
X = train[ :, 1 : ]
X.shape

(60000, 784)

In [19]:
Y = np.ndarray( shape = ( len( train ), 10 ), dtype = np.float )
for i, n in np.ndenumerate( train[ :, 0 ] ) :
    vect = np.array( [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ], dtype = np.float )
    vect[ int( n ) ] = 1.0
    Y[ i ] = vect
Y.shape

(60000, 10)

In [20]:
FFNN = FeedForwardNeuralNetwork( perceptrons_per_hidden_layer = [ 30 ] )

In [21]:
FFNN.train( X, Y, learning_rate = 3, convergence = 0.01, batch_size = 1, max_epoch = 30, max_time = 60 )

Maximum runtime encountered.


In [22]:
FFNN.score

108163.98070654711

<span style="color:#53C8FE; font-family:aparajita; font-size:18px">
    <i>A matrix of identical vectors?</i>
</span>
<br>

In [23]:
FFNN.forwardpropagation( X )

array([[3.00494983e-07, 9.04043460e-10, 6.36043136e-11, ...,
        1.68176401e-11, 1.97903819e-11, 1.33130030e-10],
       [3.00494983e-07, 9.04043460e-10, 6.36043136e-11, ...,
        1.68176401e-11, 1.97903819e-11, 1.33130030e-10],
       [3.00494983e-07, 9.04043460e-10, 6.36043136e-11, ...,
        1.68176401e-11, 1.97903819e-11, 1.33130030e-10],
       ...,
       [3.00494983e-07, 9.04043460e-10, 6.36043136e-11, ...,
        1.68176401e-11, 1.97903819e-11, 1.33130030e-10],
       [3.00494983e-07, 9.04043460e-10, 6.36043136e-11, ...,
        1.68176401e-11, 1.97903819e-11, 1.33130030e-10],
       [3.00494983e-07, 9.04043460e-10, 6.36043136e-11, ...,
        1.68176401e-11, 1.97903819e-11, 1.33130030e-10]])

In [37]:
Y[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [38]:
FFNN.forwardpropagation( X )[ 0 ]

array([3.00494983e-07, 9.04043460e-10, 6.36043136e-11, 2.83253745e-11,
       9.91102064e-09, 7.48532676e-07, 9.99999931e-01, 1.68176401e-11,
       1.97903819e-11, 1.33130030e-10])

In [36]:
Y[1]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
FFNN.forwardpropagation( X )[ 1 ]

array([3.00494983e-07, 9.04043460e-10, 6.36043136e-11, 2.83253745e-11,
       9.91102064e-09, 7.48532676e-07, 9.99999931e-01, 1.68176401e-11,
       1.97903819e-11, 1.33130030e-10])

In [34]:
Y[55000]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
FFNN.forwardpropagation( X )[ 55000 ]

array([3.00494983e-07, 9.04043460e-10, 6.36043136e-11, 2.83253745e-11,
       9.91102064e-09, 7.48532676e-07, 9.99999931e-01, 1.68176401e-11,
       1.97903819e-11, 1.33130030e-10])

In [33]:
Y[30000]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [32]:
FFNN.forwardpropagation( X )[ 30000 ]

array([3.00494983e-07, 9.04043460e-10, 6.36043136e-11, 2.83253745e-11,
       9.91102064e-09, 7.48532676e-07, 9.99999931e-01, 1.68176401e-11,
       1.97903819e-11, 1.33130030e-10])

In [31]:
 # every vector is [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ]

<h1 style="color:#F4EE00; font-family:cambria"><i>Let's try Nielson's</i></h1>
<hr>

In [28]:
#### Libraries
# Standard library
import random

# Third-party libraries
import numpy as np

class Network(object):

    def __init__(self, sizes):
        """The list ``sizes`` contains the number of neurons in the
        respective layers of the network.  For example, if the list
        was [2, 3, 1] then it would be a three-layer network, with the
        first layer containing 2 neurons, the second layer 3 neurons,
        and the third layer 1 neuron.  The biases and weights for the
        network are initialized randomly, using a Gaussian
        distribution with mean 0, and variance 1.  Note that the first
        layer is assumed to be an input layer, and by convention we
        won't set any biases for those neurons, since biases are only
        ever used in computing the outputs from later layers."""
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.biases = [np.random.randn(y, 1) for y in sizes[1:]]
        self.weights = [np.random.randn(y, x)
                        for x, y in zip(sizes[:-1], sizes[1:])]

    def feedforward(self, a):
        """Return the output of the network if ``a`` is input."""
        for b, w in zip(self.biases, self.weights):
            a = sigmoid(np.dot(w, a)+b)
        return a

    def SGD(self, training_data, epochs, mini_batch_size, eta,
            test_data=None):
        """Train the neural network using mini-batch stochastic
        gradient descent.  The ``training_data`` is a list of tuples
        ``(x, y)`` representing the training inputs and the desired
        outputs.  The other non-optional parameters are
        self-explanatory.  If ``test_data`` is provided then the
        network will be evaluated against the test data after each
        epoch, and partial progress printed out.  This is useful for
        tracking progress, but slows things down substantially."""
        if test_data: n_test = len(test_data)
        n = len(training_data)
        for j in range(epochs):
            random.shuffle(training_data)
            mini_batches = [
                training_data[k:k+mini_batch_size]
                for k in range(0, n, mini_batch_size)]
            for mini_batch in mini_batches:
                self.update_mini_batch(mini_batch, eta)
            if test_data:
                print( "Epoch {0}: {1} / {2}" ).format(
                    j, self.evaluate(test_data), n_test)
            else:
                print( "Epoch {0} complete" ).format(j)

    def update_mini_batch(self, mini_batch, eta):
        """Update the network's weights and biases by applying
        gradient descent using backpropagation to a single mini batch.
        The ``mini_batch`` is a list of tuples ``(x, y)``, and ``eta``
        is the learning rate."""
        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]
        for x, y in mini_batch:
            delta_nabla_b, delta_nabla_w = self.backprop(x, y)
            nabla_b = [nb+dnb for nb, dnb in zip(nabla_b, delta_nabla_b)]
            nabla_w = [nw+dnw for nw, dnw in zip(nabla_w, delta_nabla_w)]
        self.weights = [w-(eta/len(mini_batch))*nw
                        for w, nw in zip(self.weights, nabla_w)]
        self.biases = [b-(eta/len(mini_batch))*nb
                       for b, nb in zip(self.biases, nabla_b)]

    def backprop(self, x, y):
        """Return a tuple ``(nabla_b, nabla_w)`` representing the
        gradient for the cost function C_x.  ``nabla_b`` and
        ``nabla_w`` are layer-by-layer lists of numpy arrays, similar
        to ``self.biases`` and ``self.weights``."""
        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]
        # feedforward
        activation = x
        activations = [x] # list to store all the activations, layer by layer
        zs = [] # list to store all the z vectors, layer by layer
        for b, w in zip(self.biases, self.weights):
            z = np.dot(w, activation)+b
            zs.append(z)
            activation = sigmoid(z)
            activations.append(activation)
        # backward pass
        delta = self.cost_derivative(activations[-1], y) * \
            sigmoid_prime(zs[-1])
        nabla_b[-1] = delta
        nabla_w[-1] = np.dot(delta, activations[-2].transpose())
        # Note that the variable l in the loop below is used a little
        # differently to the notation in Chapter 2 of the book.  Here,
        # l = 1 means the last layer of neurons, l = 2 is the
        # second-last layer, and so on.  It's a renumbering of the
        # scheme in the book, used here to take advantage of the fact
        # that Python can use negative indices in lists.
        for l in range(2, self.num_layers):
            z = zs[-l]
            sp = sigmoid_prime(z)
            delta = np.dot(self.weights[-l+1].transpose(), delta) * sp
            nabla_b[-l] = delta
            nabla_w[-l] = np.dot(delta, activations[-l-1].transpose())
        return (nabla_b, nabla_w)

    def evaluate(self, test_data):
        """Return the number of test inputs for which the neural
        network outputs the correct result. Note that the neural
        network's output is assumed to be the index of whichever
        neuron in the final layer has the highest activation."""
        test_results = [(np.argmax(self.feedforward(x)), y)
                        for (x, y) in test_data]
        return sum(int(x == y) for (x, y) in test_results)

    def cost_derivative(self, output_activations, y):
        """Return the vector of partial derivatives \partial C_x /
        \partial a for the output activations."""
        return (output_activations-y)

#### Miscellaneous functions
def sigmoid(z):
    """The sigmoid function."""
    return 1.0/(1.0+np.exp(-z))

def sigmoid_prime(z):
    """Derivative of the sigmoid function."""
    return sigmoid(z)*(1-sigmoid(z))

In [29]:
train = list( zip( X, Y ) )

In [30]:
network = Network( [ 784, 30, 10 ] )

In [31]:
network.SGD( train, 30, 10, 0.01 )

FloatingPointError: overflow encountered in exp

In [31]:
'>:O'

'>:O'